version: '3.4'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python canal/manage.py migrate --noinput && \
             daphne -b 0.0.0.0 -p 8000 canal.asgi:application"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: '5432'
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      DJANGO_DEBUG: 'True'
      DJANGO_ALLOWED_HOSTS: 'localhost,127.0.0.1'
  db:
    image: postgres:11.6
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    expose:
      - "5432"
    volumes:
      - "channels_db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
  channels_db_data:
