name: Django Chat CI/CD

on:
  push:
    branches: [ main, master, develop, "feature/**", "release/**" ]
  pull_request:
    branches: [ main, master, develop ]

env:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DOCKER_IMAGE: django-channels-chat

jobs:
  verify:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: |
          requirements/development.txt
          requirements/live.txt

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/development.txt
        pip install flake8 bandit safety

    - name: Run Flake8
      run: flake8 canal

    - name: Run Security Scan
      run: |
        bandit -r canal -x canal/chat/tests,canal/chat/testing
        safety check

    - name: Run Tests
      env:
        POSTGRES_HOST: localhost
        REDIS_HOST: localhost
      run: |
        cd canal
        python manage.py test

    - name: Build and Test Docker Image
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      run: |
        docker build -t ${{ env.DOCKER_IMAGE }}:test .
        docker run --rm ${{ env.DOCKER_IMAGE }}:test python canal/manage.py test

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/development.txt
        pip install flake8 bandit safety

    - name: Run flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 canal/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Run full linting with allowed failures
        flake8 canal/ --ignore=F401,F403,F405,E402 --max-line-length=100 --statistics

    - name: Run bandit security check
      run: |
        # Skip B703 (django.mark_safe) as we've handled it safely
        bandit -r canal/ -ll --skip B703

    - name: Check dependencies for security issues
      run: |
        safety check -r requirements/development.txt

    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: canal.testing.settings
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        REDIS_HOST: localhost
        REDIS_PORT: 6379
      run: |
        cd canal
        python manage.py test

  lint-and-security:
    needs: build-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install lint & security tools
        run: |
          pip install flake8 bandit safety

      - name: Run flake8
        run: flake8 canal/ --ignore=F401,F403,F405,E402 --max-line-length=100

      - name: Run bandit security scan
        run: bandit -r canal/ -ll

      - name: Check dependencies for security issues
        run: safety check -r requirements/development.txt

  test:
    needs: [build-install, lint-and-security]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/development.txt
      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h 127.0.0.1 -p 5432 && break || sleep 1
          done
      - name: Run migrations and tests
        env:
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379
        run: |
          python canal/manage.py migrate --noinput
          python canal/manage.py test

  docker-build-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }},${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:latest
          cache-to: type=inline

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy application
        run: |
          echo "Starting deployment process..."

          # Add your deployment steps here
          # For example:
          # - Deploy using platform-specific CLI
          # - Trigger webhooks
          # - Run deployment scripts

          echo "Deployment completed."
